name: sweetchickwardrobe
description: "Baby Garment Store."
publish_to: 'none' 

  
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  get: ^4.6.6
  intl: ^0.19.0
  sizer: ^2.0.15
  fluttertoast: ^8.2.8
  bot_toast: ^4.1.3
  responsive_framework: ^1.5.1
  go_router: ^14.2.7
  dotted_line: ^3.2.2
  flutter_spinkit: ^5.2.1
  url_strategy: ^0.3.0
  hive: ^2.2.3
  transparent_image: ^2.0.1
  flutter_widget_from_html: ^0.15.2
  smooth_page_indicator: ^1.2.0
  carousel_slider: ^5.0.0
  flutter_rating_stars: ^1.1.0

  firebase_auth: ^5.1.0
  firebase_core: ^3.3.0
  firebase_analytics: ^11.3.0
  cloud_firestore: ^5.3.0
  firebase_storage: ^12.2.0
  firebase_auth_web: ^5.10.0
  csc_picker: ^0.2.7
  quill_html_editor: ^2.2.8
  syncfusion_flutter_datagrid: ^26.2.14
  desktop_window: ^0.4.0

  syncfusion_flutter_core: any
  flutter_widget_from_html_core: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
flutter:

    
  uses-material-design: true


  assets:
    - assets/images/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
